export const GET_POKEMON_STARTED = "GET_POKEMON_STARTED";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAILURE = "GET_POKEMON_FAILURE";
export const GET_POKEMON_DETAIL_STARTED = "GET_POKEMON_DETAIL_STARTED";
export const GET_POKEMON_DETAIL_SUCCESS = "GET_POKEMON_DETAIL_SUCCESS";
export const GET_POKEMON_DETAIL_FAILURE = "GET_POKEMON_DETAIL_FAILURE";
export const GET_POKEDEX_STARTED= "GET_POKEDEX_STARTED";
export const GET_POKEDEX_SUCCESS= "GET_POKEDEX_SUCCESS";
export const GET_POKEDEX_FAILURE= "GET_POKEDEX_FAILURE";
export const SEARCH_STARTED= "SEARCH_STARTED";
export const SEARCH_SUCCESS= "SEARCH_SUCCESS";
export const SEARCH_FAILURE= "SEARCH_FAILURE";

